CREATE TABLE `DnDatabaseTest` (
	`Session` SMALLINT(6) NULL DEFAULT NULL,
	`ID` INT(10) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
	`Name` TEXT NOT NULL COLLATE 'utf8_bin',
	`Health` SMALLINT(6) NOT NULL,
	`Backstory` MEDIUMTEXT NULL COLLATE 'utf8_bin',
	`Race` TINYTEXT NOT NULL COLLATE 'utf8_bin',
	`Alignment` TINYTEXT NULL COLLATE 'utf8_bin',
	`WIS` TINYINT(10) NOT NULL,
	`STR` TINYINT(10) NOT NULL,
	`DEX` TINYINT(10) NOT NULL,
	`INT` TINYINT(10) NOT NULL,
	`CHR` TINYINT(10) NOT NULL,
	`CON` TINYINT(10) NOT NULL,
	INDEX `Index 1` (`ID`)
)
COMMENT='This is a demonstration of DnDatabase'
COLLATE='utf8_bin'
ENGINE=InnoDB
;
